"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import {
  Eye,
  EyeOff,
  Download,
  Trash2,
  Save,
  Smartphone,
  Tablet,
  Monitor,
  FileCode,
  Loader2,
} from "lucide-react";
import { useBuilder, ViewportType } from "@/lib/builder-store";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import JSZip from "jszip";
import { saveAs } from "file-saver";
import { CodePreviewModal } from "./code-preview-modal";
import { generatePageCode } from "@/lib/code-generator";

export function BuilderHeader() {
  const {
    page,
    isPreviewMode,
    togglePreview,
    clearPage,
    exportPage,
    viewport,
    setViewport,
  } = useBuilder();

  const [isCodeModalOpen, setIsCodeModalOpen] = useState(false);
  const [generatedCode, setGeneratedCode] = useState("");
  const [isExporting, setIsExporting] = useState(false);

  // Handle saving JSON draft
  const handleSaveDraft = () => {
    const json = exportPage();
    const blob = new Blob([json], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${page.slug || "page"}-draft.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  // Generate code for preview
  const handleShowCode = () => {
    const { code } = generatePageCode(page);
    setGeneratedCode(code);
    setIsCodeModalOpen(true);
  };

  // Handle full ZIP download
  const handleDownloadZip = async () => {
    try {
      setIsExporting(true);
      const zip = new JSZip();

      // Generate code and images
      const { code, images } = generatePageCode(page);

      // Add page.tsx
      const appFolder = zip.folder("app");
      appFolder?.file("page.tsx", code);

      // Add images
      const publicFolder = zip.folder("public");
      const imagesFolder = publicFolder?.folder("images");

      images.forEach((img) => {
        // Remove base64 prefix if generated by code-generator it usually comes clean,
        // but let's ensure we are writing binary data
        imagesFolder?.file(
          img.filename.replace("/images/", "").replace("images/", ""),
          img.data,
          { base64: true }
        );
      });

      // Add a readme
      zip.file(
        "README.md",
        `# ${page.meta.title || "No-Code Project"}
      
Bu proje No-Code SaaS Builder ile oluşturulmuştur.

## Kurulum

1. Bu klasörü mevcut bir Next.js projesinin kök dizinine kopyalayın (veya içindekileri taşıyın).
2. Gerekli bileşenlerin \`src/components/blocks\` altında olduğundan emin olun.
3. \`npm run dev\` ile çalıştırın.
`
      );

      // Generate and download zip
      const content = await zip.generateAsync({ type: "blob" });
      saveAs(content, `${page.slug || "project"}-export.zip`);
    } catch (error) {
      console.error("Export failed:", error);
      alert("Proje dışa aktarılırken bir hata oluştu.");
    } finally {
      setIsExporting(false);
    }
  };

  const viewportButtons: {
    type: ViewportType;
    icon: typeof Smartphone;
    label: string;
  }[] = [
    { type: "mobile", icon: Smartphone, label: "Mobil" },
    { type: "tablet", icon: Tablet, label: "Tablet" },
    { type: "desktop", icon: Monitor, label: "Masaüstü" },
  ];

  return (
    <>
      <header className="h-14 border-b border-border/50 bg-background/95 backdrop-blur-sm flex items-center justify-between px-4 shrink-0">
        {/* Left - Logo & Title */}
        <div className="flex items-center gap-4">
          <motion.div
            whileHover={{ scale: 1.05 }}
            className="font-bold text-lg bg-linear-to-r from-primary to-primary/70 bg-clip-text text-transparent"
          >
            SaaS Builder
          </motion.div>

          <div className="h-4 w-px bg-border/50" />

          <div className="flex items-center gap-2">
            <Button
              variant="ghost"
              size="sm"
              onClick={handleShowCode}
              className="gap-2 text-muted-foreground hover:text-foreground"
            >
              <FileCode className="w-4 h-4" />
              <span className="hidden sm:inline">Kodu Göster</span>
            </Button>
          </div>
        </div>

        {/* Center - Viewport Controls */}
        <div className="absolute left-1/2 -translate-x-1/2 hidden md:flex items-center gap-1 bg-muted/30 p-1 rounded-lg border border-border/50">
          {viewportButtons.map((btn) => (
            <button
              key={btn.type}
              onClick={() => setViewport(btn.type)}
              className={cn(
                "p-2 rounded-md transition-all duration-200 relative",
                viewport === btn.type
                  ? "bg-background text-primary shadow-sm"
                  : "text-muted-foreground hover:text-foreground hover:bg-muted/50"
              )}
              title={btn.label}
            >
              <btn.icon className="w-4 h-4" />
              {viewport === btn.type && (
                <motion.div
                  layoutId="activeViewport"
                  className="absolute inset-0 border border-primary/20 rounded-md -z-10"
                />
              )}
            </button>
          ))}
        </div>

        {/* Right - Actions */}
        <div className="flex items-center gap-2">
          <Button
            variant="ghost"
            size="sm"
            onClick={togglePreview}
            className={cn(
              "gap-2",
              isPreviewMode && "bg-primary/10 text-primary hover:bg-primary/20"
            )}
          >
            {isPreviewMode ? (
              <>
                <EyeOff className="w-4 h-4" />
                <span className="hidden sm:inline">Düzenle</span>
              </>
            ) : (
              <>
                <Eye className="w-4 h-4" />
                <span className="hidden sm:inline">Önizle</span>
              </>
            )}
          </Button>

          <div className="h-4 w-px bg-border/50 mx-1" />

          <Button
            variant="outline"
            size="sm"
            onClick={handleSaveDraft}
            className="gap-2"
          >
            <Save className="w-4 h-4" />
            <span className="hidden sm:inline">Taslağı Kaydet</span>
          </Button>

          <Button
            size="sm"
            onClick={handleDownloadZip}
            disabled={isExporting}
            className="gap-2 bg-gradient-to-r from-primary to-primary/90 hover:opacity-90 transition-opacity"
          >
            {isExporting ? (
              <Loader2 className="w-4 h-4 animate-spin" />
            ) : (
              <Download className="w-4 h-4" />
            )}
            <span className="hidden sm:inline">Projeyi İndir</span>
          </Button>
        </div>
      </header>

      <CodePreviewModal
        isOpen={isCodeModalOpen}
        onClose={() => setIsCodeModalOpen(false)}
        code={generatedCode}
        onDownload={handleDownloadZip}
      />
    </>
  );
}
